name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.27'
        
    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -A x64 .
      
    - name: Build
      run: cmake --build . --config Release
      
    - name: Run Tests
      run: |
        ./build/src/core/Release/test_enhanced_database.exe
        ./build/src/storage/Release/btree_test.exe
        ./build/src/transaction/Release/simple_transaction_test.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.27'
        
    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
      
    - name: Build
      run: make -j$(nproc)
      
    - name: Run Tests
      run: |
        ./src/core/test_enhanced_database
        ./src/storage/btree_test
        ./src/transaction/simple_transaction_test

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.27'
        
    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release .
      
    - name: Build
      run: make -j$(nproc)
      
    - name: Run Tests
      run: |
        ./src/core/test_enhanced_database
        ./src/storage/btree_test
        ./src/transaction/simple_transaction_test